package com.epam.theatre.dao;

public enum SqlFields {

	AUDITORIUM_ID, FIRST_NAME, LAST_NAME, BIRTHDAY, PASSWORD, EVENT_SCHEDULE_ID, EVENT_DATE, EVENT_ID, TICKET_ID, TICKET_COST, SEAT, EVENT_RATING, BASE_PRICE, EVENT_NAME, EMAIL, COUNTER_ID, CLASS_NAME, TYPE_ID, TYPE_NAME, COUNTER_VALUE, DISCOUNT, COUNTER_NAME, CUSTOMER_ID, ROLE;

}
